layout: siderbar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 50
  exclude:
    archived: true
    forks: true
    projects:
      - ihlassovbetov.github.io

social_media:
  website: https://ihlas.sovbetov.com
  linkedin: yhlas-sovbetov
  facebook: ihlassovbetov
  twitter: ihlassovbetov
  github: ihlassovbetov
  email: ihlasnobatovich@gmail.com
  # reddit: your_username
  # youtube: your_username

